name = "zino-example"
version = "1.0.0"

[main]
host = "127.0.0.1"
port = 8080

[database]

[[postgres]]
host = "postgres.orb.local"
port = 5432
database = "postgres"
username = "postgres"
password = "postgres_password"
